name: Build compile javascript and css

on: [push]

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install dependency and build dist
        run: |
          npm i 
          npm run build
          rm -rf node_modules
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
